Python Array (List)

A Python list is a built-in data structure that can store different data types.

Features:
Can store mixed data types (int, float, string, etc.)

Slower for numerical operations

Uses more memory

Mathematical operations require loops

In [1]:
a = [10, 20, 30]
b = [1, 2, 3]
print(a + b)

[10, 20, 30, 1, 2, 3]


In [2]:
result = []
for i in range(3):
    result.append(a[i] + b[i])
print(result)

[11, 22, 33]


In [3]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)

[11 22 33]


When you create a NumPy array, NumPy automatically converts all elements to a single common data type.

In [4]:
import numpy as np

arr = np.array([10, 2.5, 3])
print(arr)
print(arr.dtype)

[10.   2.5  3. ]
float64


In [5]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2.5, 3])

print(a + b)

[11.  22.5 33. ]


In [6]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [7]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np

In [9]:
# Integer array
arr_int = np.array([10, 20, 30, 40, 50])

# Float array
arr_float = np.array([1.5, 2.3, 3.8, 4.1])

# Mixed type array
arr_mixed = np.array([10, 2.5, "A", True])

print(arr_int)
print(arr_float)
print(arr_mixed)

[10 20 30 40 50]
[1.5 2.3 3.8 4.1]
['10' '2.5' 'A' 'True']


In [10]:
a = [10, 20, 30]
b = [1, 2, 3]


In [11]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])


print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


print("Mean:", np.mean(a))
print("Max:", np.max(a))
print("Min:", np.min(a))
print("Standard Deviation:", np.std(a))

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Mean: 25.0
Max: 40
Min: 10
Standard Deviation: 11.180339887498949


Pandas Series is a one-dimensional labeled array that can hold data of any type (integer, float, string, Python objects, etc.). 
It is similar to a column in an Excel spreadsheet or a database table. 
In this article we will study Pandas Series which is a useful one-dimensional data structure in Python.

In [12]:
import pandas as pd

In [13]:
import pandas as pd

data = [1, 2, 3, 4]
 
ser = pd.Series(data)
print(ser)

0    1
1    2
2    3
3    4
dtype: int64


In [14]:
import pandas as pd
import numpy as np

data = np.array(['g','e','e','k','s','f', 'o','r','g','e','e','k','s'])
ser = pd.Series(data)

print(ser[:5])

0    g
1    e
2    e
3    k
4    s
dtype: object


In [21]:
# Syntex:
# pandas.Series(data, index, dtype, copy)

# How to use:copy
# deep=True: Creates a Deep Copy. It copies both the indices and the actual data. Modifications to new_s will not affect s.
# deep=False: Creates a Shallow Copy. It only copies references to the data.

# Where to use:
# Experimental Work: When you want to try different filters or transformations without ruining your main dataset.

# Avoiding Warnings: Prevents the SettingWithCopyWarning when you extract a column from a DataFrame and want to modify it independently. 

days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
temps = np.array([30, 32, 31, 29, 28])
s = pd.Series(temps, index=days,dtype='float64',copy=True)
print(s)

# Copy Parameter કેવી રીતે વાપરવું:

# deep=True: Deep Copy બનાવે છે
# આ indices અને actual data બંને ની copy બનાવે છે
# નવા series (new_s) માં changes કરો તો original series (s) પર કોઈ અસર નહીં થાય
# બંને completely અલગ બની જાય છે - જેમ કે બે અલગ notebooks


# deep=False: Shallow Copy બનાવે છે

# આ ફક્ત data નો reference copy કરે છે, actual data નહીં
# એક જ data ને બે નામો આપે છે જેવું
# નવા series માં changes કરો તો original પણ change થઈ શકે છે

# કયારે વાપરવું (Where to use):
# 1. Experimental Work માટે:
# જ્યારે તમે different filters અથવા transformations try કરવા માંગો છો અને તમારું main dataset ખરાબ કરવું નથી. જેમ કે:
#Original data safe રાખવો હોય
# નવા experiments કરવા હોય પણ backup જોઈએ
# Multiple versions ની જરૂર હોય

# 2. Warnings ટાળવા માટે:
# SettingWithCopyWarning prevent કરે છે જ્યારે તમે DataFrame માંથી column extract કરો છો અને એને independently modify કરવું હોય. આ warning આવે છે જ્યારે pandas ને ખબર નથી કે તમે original data change કરો છો કે copy

Mon    30.0
Tue    32.0
Wed    31.0
Thu    29.0
Fri    28.0
dtype: float64


In [22]:
print(s[0])
print(s[1:4])

30.0
Tue    32.0
Wed    31.0
Thu    29.0
dtype: float64


/var/folders/m_/mkmgvrh50sjbfhzz0vscx1tw0000gn/T/ipykernel_75777/47213271.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])


Access using labels

In [23]:
print(s['Mon'])
print(s['Mon':'Thu'])

30.0
Mon    30.0
Tue    32.0
Wed    31.0
Thu    29.0
dtype: float64


Common series method

In [24]:
print(s.head())


Mon    30.0
Tue    32.0
Wed    31.0
Thu    29.0
Fri    28.0
dtype: float64


In [47]:
print(s.tail())


Mon    30
Tue    32
Wed    31
Thu    29
Fri    28
dtype: int64


In [48]:
print(s.value_counts())
print(s.describe())

30    1
32    1
31    1
29    1
28    1
Name: count, dtype: int64
count     5.000000
mean     30.000000
std       1.581139
min      28.000000
25%      29.000000
50%      30.000000
75%      31.000000
max      32.000000
dtype: float64


Create Dataframe from dictionary

What is a DataFrame?

A DataFrame is a two-dimensional labeled data structure (rows × columns).

Stores multiple columns

Each column is a Series

Has row index and column names

Similar to an Excel sheet / database table

In [63]:
import pandas as pd

data = [1, 2, 3, 4]
 
ser = pd.DataFrame(data)
print(ser)

   0
0  1
1  2
2  3
3  4


create a dataframe from 2d Array

In [61]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
df_np = pd.DataFrame(arr, columns=['Col1', 'Col2'])
print(df_np)

   Col1  Col2
0     1     2
1     3     4
2     5     6


create a dataframe from dictionary

In [139]:
data = {
'Name': ['Amit', 'Neha', 'Rahul', 'Priya'],
'Maths': [78, 85, 67, 92],
'Science': [80, 88, 70, 95]
}

df = pd.DataFrame(data)
print(df)

    Name  Maths  Science
0   Amit     78       80
1   Neha     85       88
2  Rahul     67       70
3  Priya     92       95


In [140]:
df['Name']

0     Amit
1     Neha
2    Rahul
3    Priya
Name: Name, dtype: object

In [141]:
df['Maths']

0    78
1    85
2    67
3    92
Name: Maths, dtype: int64

In [142]:
df.head()

Name  Maths  Science
0   Amit     78       80
1   Neha     85       88
2  Rahul     67       70
3  Priya     92       95

In [143]:
df.tail()

Name  Maths  Science
0   Amit     78       80
1   Neha     85       88
2  Rahul     67       70
3  Priya     92       95

In [144]:
df.shape

(4, 3)

In [145]:
df.columns

Index(['Name', 'Maths', 'Science'], dtype='object')

In [146]:
df.dtypes

Name       object
Maths       int64
Science     int64
dtype: object

In [147]:
df.rename(columns={'Maths': 'Mathematics'}, inplace=True) #inplace true means it will change the original dataframe 

In [148]:
df

Name  Mathematics  Science
0   Amit           78       80
1   Neha           85       88
2  Rahul           67       70
3  Priya           92       95

Inner df[...]	Creates Boolean condition
Outer df[...]	Filters rows using that condition

In [149]:
df[df['Mathematics'] > 80] #have to use Mathematics


Name  Mathematics  Science
1   Neha           85       88
3  Priya           92       95

In [150]:
df

Name  Mathematics  Science
0   Amit           78       80
1   Neha           85       88
2  Rahul           67       70
3  Priya           92       95

In [151]:
df['Mathematics'] > 80

0    False
1     True
2    False
3     True
Name: Mathematics, dtype: bool

In [152]:
df['Total'] = df['Mathematics'] + df['Science']

In [153]:
df

Name  Mathematics  Science  Total
0   Amit           78       80    158
1   Neha           85       88    173
2  Rahul           67       70    137
3  Priya           92       95    187

In [154]:
df['Percentage'] = (df['Total'] / 200) * 100

In [155]:
df

Name  Mathematics  Science  Total  Percentage
0   Amit           78       80    158        79.0
1   Neha           85       88    173        86.5
2  Rahul           67       70    137        68.5
3  Priya           92       95    187        93.5

In [156]:
df.sort_values(by='Percentage')

Name  Mathematics  Science  Total  Percentage
2  Rahul           67       70    137        68.5
0   Amit           78       80    158        79.0
1   Neha           85       88    173        86.5
3  Priya           92       95    187        93.5

In [157]:
df.sort_values(by='Percentage', ascending=False)

Name  Mathematics  Science  Total  Percentage
3  Priya           92       95    187        93.5
1   Neha           85       88    173        86.5
0   Amit           78       80    158        79.0
2  Rahul           67       70    137        68.5

In [158]:
df.set_index('Name', inplace=True)

In [159]:
df

Mathematics  Science  Total  Percentage
Name                                          
Amit            78       80    158        79.0
Neha            85       88    173        86.5
Rahul           67       70    137        68.5
Priya           92       95    187        93.5

In [160]:
df.to_csv('student_marks.csv', index=False)

In [161]:
new_df = pd.read_csv('student_marks.csv')

In [162]:
new_df

Mathematics  Science  Total  Percentage
0           78       80    158        79.0
1           85       88    173        86.5
2           67       70    137        68.5
3           92       95    187        93.5

In [163]:
df.drop('Science',axis=1 , inplace=True)# axis=1 is column and axis=0 means row

In [164]:
df

Mathematics  Total  Percentage
Name                                 
Amit            78    158        79.0
Neha            85    173        86.5
Rahul           67    137        68.5
Priya           92    187        93.5

In [132]:
new_df

Mathematics  Science  Total  Percentage
0           78       80    158        79.0
1           85       88    173        86.5
2           67       70    137        68.5
3           92       95    187        93.5

In [166]:
print(new_df.loc[2])

Mathematics     67.0
Science         70.0
Total          137.0
Percentage      68.5
Name: 2, dtype: float64


In [167]:
print(new_df.loc[1:3])

   Mathematics  Science  Total  Percentage
1           85       88    173        86.5
2           67       70    137        68.5
3           92       95    187        93.5


In [171]:
new_df

Mathematics  Science  Total  Percentage
0           78       80    158        79.0
1           85       88    173        86.5
2           67       70    137        68.5
3           92       95    187        93.5

In [173]:
print(new_df.iloc[0:3, 1:3]) #iloc(rows,columns)

   Science  Total
0       80    158
1       88    173
2       70    137


load data from csv file 

In [174]:
df_weather = pd.read_csv('Downloads/weather_data.csv')

In [175]:
df_weather

Day  Temperature  Humidity  WindSpeed
0  Mon           30        60         10
1  Tue           32        65         12
2  Wed           31        63         11
3  Thu           29        58          9
4  Fri           28        55          8